### ISSUE TITLE
Missing image files in build

### ISSUE THREAD

**Issue by ujwaldreamztech** [paljs/gatsby-admin-template#85]
Hello,

When I upload the public folder to an apache server, it doesn't show any image files. However the same build is showing images when uploaded to netlify. Could you tell us what configuration is needed to make this work in apache?

<img width="909" alt="missing icon" src="https://user-images.githubusercontent.com/53903670/92099625-5f042180-edf8-11ea-8e3c-c0a66374a0f8.png">
<img width="908" alt="working icon" src="https://user-images.githubusercontent.com/53903670/92099634-60354e80-edf8-11ea-9013-2ad5a9fa6131.png">

**Comment by AhmedElywa** [comment]
@ujwaldreamztech sorry but it's not my issue I think you need to search about deploy [gatsbyjs](https://www.gatsbyjs.org/ ) to apache server
