### ISSUE TITLE
Layout Page

### ISSUE THREAD

**Issue by RaJiska** [paljs/gatsby-admin-template#90]
The layout page returns a 404 and is nowhere to be found in the code. Is this a mistake or some kind of forgotten / abandoned feature ?

**Comment by AhmedElywa** [comment]
Can you send a screenshot of the error?

**Comment by RaJiska** [comment]
Available at address:
https://github.com/paljs/gatsby-admin-template

![image](https://user-images.githubusercontent.com/6755943/101781565-e47e2880-3aef-11eb-825c-ce4b8df56e9e.png)

**Comment by AhmedElywa** [comment]
Oh, my bad there is no page call form layout. I will remove it from the menu.
thanks
